services:
  - type: web
    name: healthcare-backend
    env: node
    buildCommand: cd backend && npm install && npx prisma generate && npm run build
    startCommand: cd backend && npx prisma migrate deploy && npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: healthcare-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: "24h"
      - key: CORS_ORIGIN
        value: "*"

databases:
  - name: healthcare-db
    databaseName: healthcare_db
    user: healthcare_user